# Generated by Django 4.0.6 on 2022-08-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power_plant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_jeju', models.BooleanField(default=False)),
                ('supply_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='power_plant.powerplant')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.certificate')),
            ],
        ),
    ]
