# Generated by Django 4.0.1 on 2022-08-28 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_transaction_executed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='registered_time',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 20, 23, 26, 749298)),
        ),
    ]
