# Generated by Django 4.0.1 on 2022-08-28 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_alter_transaction_registered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='registered_time',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 20, 40, 58, 992115)),
        ),
    ]
