# Generated by Django 4.0.1 on 2022-08-28 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_alter_transaction_registered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='executed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 20, 57, 6, 270927)),
        ),
    ]
